apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-service
spec:
  selector:
    matchLabels:
      app: auction-service
  template:
    metadata:
      labels:
        app: auction-service
    spec:
      containers:
      - name: auction-service
        image: ghanem22/auction-service:latest
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: auction-secret
                key: connString
          - name: RabbitMQ__Username
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: username
          - name: RabbitMQ__Password
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: password
        envFrom:
          - configMapRef:
              name: auction-service-config
        ports:
        - containerPort: 80
          name: web
        - containerPort: 7777
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: auction-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-service
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 7777
    targetPort: 7777
    name: grpc

