apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-service
spec:
  selector:
    matchLabels:
      app: bid-service
  template:
    metadata:
      labels:
        app: bid-service
    spec:
      containers:
      - name: bid-service
        image: ghanem22/bid-service:latest
        env:
          - name: ConnectionStrings__BidDbConnection
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: connString
          - name: RabbitMQ__Username
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: username
          - name: RabbitMQ__Password
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: password
        envFrom:
          - configMapRef:
              name: bid-service-config
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-service
  ports:
  - port: 80
    targetPort: 80

