apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: ghanem22/identity-service:latest
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: identity-secret
                key: connString
        envFrom:
          - configMapRef:
              name: identity-service-config
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-clusterip
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
  - port: 80
    targetPort: 80

