apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-service
spec:
  selector:
    matchLabels:
      app: notify-service
  template:
    metadata:
      labels:
        app: notify-service
    spec:
      containers:
      - name: notify-service
        image: ghanem22/notify-service:latest
        env:
          - name: RabbitMQ__Username
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: username
          - name: RabbitMQ__Password
            valueFrom:
              secretKeyRef:
                name: rabbit-secret
                key: password
        envFrom:
          - configMapRef:
              name: notify-service-config
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: notify-clusterip
spec:
  type: ClusterIP
  selector:
    app: notify-service
  ports:
  - port: 80
    targetPort: 80

