apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-service
spec:
  selector:
    matchLabels:
      app: webapp-service
  template:
    metadata:
      labels:
        app: webapp-service
    spec:
      containers:
      - name: webapp-service
        image: ghanem22/web-app:latest
        env:
          - name: AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: webapp-secret
                key: authSecret
        envFrom:
          - configMapRef:
              name: webapp-service-config
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: webapp-service
  ports:
  - port: 3000
    targetPort: 3000

